### ISSUE TITLE
StorageESP error

### ISSUE THREAD

**Issue by justamind** [spaceclouds42/meteor-client-1.17-issues#1]
Unreported exception thrown!
java.lang.NullPointerException
    at minegame159.meteorclient.modules.render.StorageESP.lambda$new$0(StorageESP.java:125)
    at me.zero.alpine.listener.Listener.invoke(Listener.java:97)
    at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:79)
    at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
    at me.zero.alpine.bus.EventManager.post(EventManager.java:79)
    at net.minecraft.class_757.handler$zcb000$onRenderWorld(class_757.java:1005)
    at net.minecraft.class_757.method_3188(class_757.java:759)
    at net.minecraft.class_757.method_3192(class_757.java:553)
    at net.minecraft.class_310.method_1523(class_310.java:1053)
    at net.minecraft.class_310.method_1514(class_310.java:688)
    at net.minecraft.client.main.Main.main(Main.java:215)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

**Comment by spaceclouds42** [comment]
toggling it using key bind? or just turning it off?

**Comment by justamind** [comment]
I will check rn

**Comment by justamind** [comment]
nevermind all of this, I was using an old commit

**Comment by justamind** [comment]
woah nevermind again
When I looked away and looked back, it crashed

**Comment by spaceclouds42** [comment]
:concern:

**Comment by spaceclouds42** [comment]
is StorageESP the only module you have on when it crashes? also send that most recent crash log

**Comment by spaceclouds42** [comment]
```
java.lang.NullPointerException: Unexpected error
	at minegame159.meteorclient.modules.render.StorageESP.lambda$new$0(StorageESP.java:126)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:97)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:79)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:79)
	at net.minecraft.client.render.GameRenderer.handler$zcb000$onRenderWorld(GameRenderer.java:869)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:630)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:427)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1067)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:681)
	at net.minecraft.client.main.Main.main(Main.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by SpaceClouds42** [comment]
It's the CommandSuggestor Mixin
that's one of them atleast
Caused by: org.spongepowered.asm.mixin.injection.throwables.**InjectionError**: LVT in **net/minecraft/client/gui/screen/CommandSuggestor::refresh()V** has incompatible changes at opcode 4 in callback **net/minecraft/client/gui/screen/CommandSuggestor::onRefresh**.
Expected: [**Ljava/lang/String;, Lcom/mojang/brigadier/StringReader;**]
   Found: []
