### ISSUE TITLE
Opening chat crashes the game

### ISSUE THREAD

**Issue by justamind** [spaceclouds42/meteor-client-1.17-issues#2]
[crash-2021-01-09_20.18.55-client.txt](https://github.com/SpaceClouds42/meteor-client-1.17-issues/files/5792071/crash-2021-01-09_20.18.55-client.txt)

**Comment by spaceclouds42** [comment]
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 1/9/21 8:18 PM
Description: Unexpected error

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.client.gui.screen.ChatScreen.init(ChatScreen.java:41)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:346)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient.java:943)
	at net.minecraft.client.MinecraftClient.openChatScreen(MinecraftClient.java:912)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:1689)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1533)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1045)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:681)
	at net.minecraft.client.main.Main.main(Main.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/client/gui/screen/CommandSuggestor::refresh()V has incompatible changes at opcode 4 in callback net/minecraft/client/gui/screen/CommandSuggestor::onRefresh.
Expected: [Ljava/lang/String;, Lcom/mojang/brigadier/StringReader;]
   Found: []
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 23 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.client.gui.screen.ChatScreen.init(ChatScreen.java:41)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:346)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient.java:943)
	at net.minecraft.client.MinecraftClient.openChatScreen(MinecraftClient.java:912)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient.java:1689)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Player433'/244, l='ClientLevel', x=-154.27, y=66.00, z=40.54]]
	Chunk stats: 225, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (-176,64,32), Section: (at 0,0,0 in -11,4,2; chunk contains blocks -176,0,32 to -161,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2564 game time, 2564 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:357)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2180)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:702)
	at net.minecraft.client.main.Main.main(Main.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 20w51a
	Minecraft Version ID: 20w51a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_275, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 630189048 bytes (600 MB) / 1299709952 bytes (1239 MB) up to 1897922560 bytes (1810 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric: Fabric API 0.29.3+1.17
		fabric-api-base: Fabric API Base 0.2.0+eaafab808e
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+836e66a38e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+9f7a74238e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+9f7a74238e
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+c67237118e
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+bee3a8868e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+880269e68e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d8e
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+e1f1abb18e
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+05c818888e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+9f7a74238e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+9f7a74238e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+c67237118e
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+9f7a74238e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+c67237118e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c68e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+9f7a74238e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.0+8f5b7a468e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+0c3d83a58e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+9f7a74238e
		fabric-models-v0: Fabric Models (v0) 0.2.0+c67237118e
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+c67237118e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+bee3a8868e
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+96f0bfaa8e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.2+9f7a74238e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+9f7a74238e
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+c67237118e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+836e66a38e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+c67237118e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+e1f1abb18e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.0.3+0c3d83a58e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+9f7a74238e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+9f7a74238e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+9f7a74238e
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+ed5162f88e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+53f160a88e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.3+9f7a74238e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+c67237118e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+e1f1abb18e
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+9f7a74238e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+9f7a74238e
		fabricloader: Fabric Loader 0.10.8
		meteor-client: Meteor Client 0.3.9
		minecraft: Minecraft 1.17-alpha.20.51.a
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.79, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

-- Meteor Client --
Version: 0.3.9

[Render]:
Entity Owner (entity-owner)

[Misc]:
Discord Presence (discord-presence)
```

**Comment by spaceclouds42** [comment]
> It's the CommandSuggestor Mixin
> that's one of them atleast
> Caused by: org.spongepowered.asm.mixin.injection.throwables.**InjectionError**: LVT in **net/minecraft/client/gui/screen/CommandSuggestor::refresh()V** has incompatible changes at opcode 4 in callback **net/minecraft/client/gui/screen/CommandSuggestor::onRefresh**.
> Expected: [**Ljava/lang/String;, Lcom/mojang/brigadier/StringReader;**]
>    Found: []

thx @justamind
